# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_dirent
    test_fault_wrappers_fnmatch
    test_fault_wrappers_ftw
    test_fault_wrappers_glob
    test_fault_wrappers_libgen
    test_fault_wrappers_stdio
    test_fault_wrappers_stdlib
    test_fault_wrappers_sys_stat
    test_fault_wrappers_sys_statvfs
    test_fault_wrappers_unistd
)
